## Python Basics Exercise
This exercise is designed to test your skills on basic Python programming, `numpy` and `pandas`.

Place your answers within the code blocks that have the comment.

```python
# your code here
```

Make sure to remove or comment the line below to be able to proceed. It's only placed there as a reminder that the function has not yet been implemented.
```python
raise NotImplementedError
```

## Note on "test scripts"

The code bloock following the function definition are "unit tests" which are code blocks which test if the function you implemented is correct or not. It will not print an output **if the conditions are met** (meaning the answer is correct). The current output for "Exercise 1" shows an example of when the code is correct and there's no errors, while the output for "Exercise 2" shows an example of what it would look like if something is incorrect.

---

In [1]:
# Place your imports here
import numpy as np
import pandas as pd

**Exercise 1.** Create a function that generates a list containing values from 0 to n-1. **(1 pt.)**

In [2]:
def exercise_1(n):
    # your code here.
     return list (range (n))

n = 5
ans = exercise_1(n)
ans

n = 25
ans = exercise_1(n)
ans

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [3]:
# these are test scripts
ans = exercise_1(5)
assert ans==[0, 1, 2, 3, 4]

ans = exercise_1(25)
assert ans==[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

**Exercise 2.** Create a function that turns the list into a numpy array **(1 pt.)**

In [4]:
def exercise_2(nums):
    # your code here.
    return np.array(nums, dtype = int)

nums = 5
ans = exercise_2(nums)
ans

nums = 5
ans = exercise_2(exercise_1(nums))
ans

nums = 25
ans = exercise_2(exercise_1(nums))
ans

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
ans = exercise_2([0, 1, 2, 3, 4])
assert (ans==np.arange(5)).sum()==5

ans = exercise_2(exercise_1(5))
assert (ans==np.arange(5)).sum()==5

ans = exercise_2(exercise_1(25))
assert (ans==np.arange(25)).sum()==25

**Exercise 3.** Create a function that accepts 2 parameters: 
 - nums - a list of integer
 - n - a single integer number
 
The function adds n to all the numbers in nums.

**(1 pt.)**

In [6]:
def exercise_3(nums, n):
    # your code here.
    arr = np.array(nums)
    ans = arr + n
    return ans 
        
nums = list (range (4+1))
n = 20
ans = exercise_3(nums, n)
ans

nums = list (range (2+1))
n = 60
ans = exercise_3(nums, n)
ans

array([60, 61, 62])

In [7]:
ans = exercise_3([0, 1, 2, 3, 4], 20)
assert (ans==np.arange(20, 25)).sum()==5

ans = exercise_3([0, 1, 2], 60)
assert (ans==np.arange(60, 63)).sum()==3

**Exercise 4.** Create a function that accepts a list of numbers as input and returns the first number that has a lower than the number preceding it. If there is none, return `None`.

**(2 pts.)**

In [8]:
def exercise_4(nums):
    # your code here.
    arr = np.array(nums)
    items = len(nums)
    steps = items-1
    
    first = arr[0]
    #print ("first:",first)
    
    last = arr[steps]
    #print ("last:", last)
    
    #print ("total number of items:",items)
    
    for i in range(steps):
        #print ("step number:",i+2," of ",items)

        val = arr[i+1]
        #print ("current value checked:",val)
        
        before = arr[i]
        #print ("value before:",before)
        
        if before==last:
            continue
        
        if val == first:
            continue
        
        if val == last:
            ans=None
            break
        
        if val<before:
            ans=val
            #print ("item number:",i+2,", value:",val)
            break
    return ans
        
nums = list ([0.79, 4, 11.8, 99])
ans = exercise_4(nums)
ans

nums = list ([0.79, 4, 11.8, 99, 0.4, 76, 55, 66])
ans = exercise_4(nums)
ans

nums = list ([0.79, 4, 4, 11.0, 11, -10, -11, 12])
ans = exercise_4(nums)
ans

-10.0

In [9]:
ans = exercise_4([0.79, 4, 11.8, 99])
assert ans==None 

ans = exercise_4([0.79, 4, 11.8, 99, 0.4, 76, 55, 66])
assert ans==0.4

ans = exercise_4([0.79, 4, 4, 11.0, 11, -10, -11, 12])
assert ans==-10

**Exercise 5.** Create a function that returns a list of prime factors of a number.

**(2 pts.)**

In [10]:
def exercise_5(n):
    # your code here.
    fac = []
    d = 2
    while n > 1:
        while n % d == 0:
            fac.append(d)
            n = n/d
        d = d + 1
        #print ("added factor:", fac)
    
    #return uniques
    fac_set = set(fac) 
    unique_list = (list(fac_set))       
    return sorted (unique_list)
    
exercise_5(1)

exercise_5(4)

exercise_5(1265)

exercise_5(3674)

[2, 11, 167]

In [11]:
ans = exercise_5(1)
assert ans==[]

ans = exercise_5(4)
assert ans==[2] 

ans = exercise_5(1265)
assert ans==[5, 11, 23]

ans = exercise_5(3674)
assert ans==[2, 11, 167]

**Exercise 6.** Create a function that has 3 parameters: list of integers (num), integer number (n1), and another integer number (n2). The function will return a list of integers that are multiples of either n1 or n2.

**(2 pts.)**

In [12]:
def exercise_6(num, n1, n2):
    # your code here.   
    ans1 = []
    ans2 = []
    ans3 = []
    ans1.append(list(range(0, num, n1)))
    #print ("ans1:",ans1)
    ans2.append(list(range(0, num, n2)))
    #print ("ans2:",ans2)
    ans3 = ans1+ans2
    #print ("ans3:",ans3)
    
    #flatten list
    result = []
    extend = result.extend
    for i in ans3:
        extend(i)
    #print ("result pre sort:",result)
    
    #return uniques
    result_set = set(result)  
    unique_list = (list(result_set))
    return sorted(unique_list)

num = 20 
n1 = 3
n2 = 4
ans = exercise_6(num, n1, n2)
ans.pop(0)
ans


num = 300
n1 = 17
n2 = 27
ans = exercise_6(num, n1, n2)
ans.pop(0)
ans


[17,
 27,
 34,
 51,
 54,
 68,
 81,
 85,
 102,
 108,
 119,
 135,
 136,
 153,
 162,
 170,
 187,
 189,
 204,
 216,
 221,
 238,
 243,
 255,
 270,
 272,
 289,
 297]

In [13]:
def exercise_6(num, n1, n2):
    # your code here.
    
    #print("list of integers:",num)
    
    listlength=len(num)
    #print("list length:",listlength)
    
    #print("1st least common multiple:",n1)
    #print("2nd least common multiple:",n2)
    
    arr = np.array(num)
    print (arr)
    
    maxint = np.max(num)
    #print ("maximum integer:",maxint)
    
    mults1 = []
    arr1 = np.array(mults1)
    mults2 = []
    arr2 = np.array(mults2)
    mults3 = []
    multstot = np.array(mults3)
    
    
    #first set of multiples
    i=1
    n1mult = n1

    while n1mult<maxint:
            #print ("sequence:",i)
            n1mult=n1*i
            #print (i," multiple of",n1,":",n1mult)
            arr1=np.append (arr1,n1mult)
            #print ("list of multiples for n1",arr1)
            maxmult1 =np.max(arr1)
            i=i+1
            
    #second set of multiples
    i=1
    n2mult = n2

    while n2mult<=maxint:
            #print ("sequence:",i)
            n2mult=n2*i
            #print (i," multiple of",n2,":",n2mult)
            arr2=np.append (arr2,n2mult)
            #print ("list of multiples for n2",arr2)
            maxmult2 =np.max(arr2)
            i=i+1
            
    multstot = np.append(arr1,arr2)
    #print ("combined multiples of:",n1,"and",n2,":",multstot)
    
    filtmultvmax = multstot [multstot < maxint]
    #print ("filtered combined multiples of:",n1,"and",n2,":",filtmultvmax)
    
    #unique list 
    filt_set = set(filtmultvmax) 
    unique_list = (list(filt_set))       
    
    return sorted (unique_list)
    
    
num = list (range (20))
n1 = 3
n2 = 4
ans = exercise_6(num, n1, n2)
ans


num = list (range (300))
n1 = 17
n2 = 27
ans = exercise_6(num, n1, n2)
ans




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 2

[17.0,
 27.0,
 34.0,
 51.0,
 54.0,
 68.0,
 81.0,
 85.0,
 102.0,
 108.0,
 119.0,
 135.0,
 136.0,
 153.0,
 162.0,
 170.0,
 187.0,
 189.0,
 204.0,
 216.0,
 221.0,
 238.0,
 243.0,
 255.0,
 270.0,
 272.0,
 289.0,
 297.0]

In [14]:
ans = exercise_6(np.arange(20), 3, 4)
assert ans==[3, 4, 6, 8, 9, 12, 15, 16, 18]

ans = exercise_6(np.arange(300), 17, 27)
assert ans==[17, 27, 34, 51, 54, 68, 81, 85, 102, 108, 119, 135, 136, 153, 162, 170, 187, 189, 204, 216, 221, 238, 243, 255, 270, 272, 289, 297]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 2

**Exercise 7.** Create a function that reads the Titanic dataset (`data/train.csv`) and returns the ages (in list form) of first 5 (based on index) female passengers who survived .

**(2 pts.)**

In [59]:
def exercise_7():
    # your code here.
    DATA_DIR = "./data/"
    titanic = pd.read_csv("data/train.csv")
    #print (titanic)
    female = titanic[titanic.Sex=="female"]
    #print (female)
    survived = female[female.Survived==1]
    #print (survived)
    age=survived['Age'].head()
    agelist=age.values.tolist()
    agelistnp = list(np.int_(agelist))
    return agelistnp


exercise_7()

    
    

[38, 26, 35, 27, 14]

In [60]:
assert exercise_7()==[38, 26, 35, 27, 14]

**Exercise 8.** Create a function that reads the Titanic dataset (`data/train.csv`) and returns the average fare of all female passengers who survived and have an age greater than 30. Format the result by rounding up to 2 decimal values. Make sure the data type is float.

**(2 pts.)**

In [65]:
def exercise_8():
    # your code here.
    DATA_DIR = "./data/"
    titanic = pd.read_csv("data/train.csv")
    #print (titanic)
    female = titanic[titanic.Sex=="female"]
    #print (female)
    survived = female[female.Survived==1]
    #print (survived)
    above30 = survived[survived.Age>30]
    #print (above30)
    faremean = above30['Fare'].mean()
    #print ("Average Fare of Surviving Females, above 30yo:")
    faremeanround = round(faremean,2)
    return faremeanround


exercise_8()


71.16

In [66]:
assert exercise_8()==71.16